<h2>Machine Learning-:</h2>
<p> Ml predict future or solve the problem based on the previous data.it find hidden patterns and relationship to solve the problem
ML learn algorithams patterns based on the example of task </p>
<h3> partition in ML</h3>
<p> 1) supervised learning:- classification, regression <br> 2) unsupervised learning</p>
y=price ,x= other columns
# pridict y base on the x
#regression-- continuous nature
# Ml algo does not take any alphaberic value it take only numerical value

In [66]:
import pandas as pd
import numpy as np

In [67]:
#steps :->>>
#1) gathering the data(fromcloud, database)
#2) data preparation

In [98]:
df=pd.read_csv("Used_Bikes.csv")
df.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [69]:
# step 2)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  object
 1   price       32648 non-null  float64
 2   city        32648 non-null  object
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  object
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  object
dtypes: float64(4), object(4)
memory usage: 2.0+ MB

In [70]:
# 5000 , 2 year age , hero, second hand, splender then tell the price of the bike with the help of ML
#y=price ,x= other columns
# pridict y base on the x
#regression-- continuous nature
# Ml algo does not take any alphaberic value it take only numerical value

In [71]:
df.drop_duplicates(inplace=True)

In [72]:
df.isnull().sum()   # missing value

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [73]:
df['brand'].value_counts()>=10

brand
Bajaj               True
Royal Enfield       True
Hero                True
Honda               True
Yamaha              True
TVS                 True
KTM                 True
Suzuki              True
Harley-Davidson     True
Kawasaki            True
Hyosung             True
Mahindra            True
Benelli             True
Triumph             True
Ducati              True
BMW                 True
Jawa               False
Indian             False
MV                 False
Rajdoot            False
LML                False
Yezdi              False
Ideal              False
Name: count, dtype: bool

In [74]:
brand_list=['Bajaj', 'Royal Enfield', 'Hero', 'Honda', 'Yamaha', 'TVS', 'KTM',
       'Suzuki', 'Harley-Davidson', 'Kawasaki', 'Hyosung', 'Mahindra',
       'Benelli', 'Triumph', 'Ducati', 'BMW']

In [75]:
df=df[df['brand'].isin(brand_list)]
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [76]:
catgorical=df.select_dtypes(include='O')
catgorical.head()

                              bike_name       city        owner          brand
0    TVS Star City Plus Dual Tone 110cc  Ahmedabad  First Owner            TVS
1           Royal Enfield Classic 350cc      Delhi  First Owner  Royal Enfield
2                  Triumph Daytona 675R      Delhi  First Owner        Triumph
3                  TVS Apache RTR 180cc  Bangalore  First Owner            TVS
4  Yamaha FZ S V 2.0 150cc-Ltd. Edition  Bangalore  First Owner         Yamaha

In [77]:
numerical=df.select_dtypes(exclude='O')
numerical.head()

      price  kms_driven  age  power
0   35000.0     17654.0  3.0  110.0
1  119900.0     11000.0  4.0  350.0
2  600000.0       110.0  8.0  675.0
3   65000.0     16329.0  4.0  180.0
4   80000.0     10000.0  3.0  150.0

In [78]:
catgorical['owner'].value_counts()

owner
First Owner             6628
Second Owner             586
Third Owner               83
Fourth Owner Or More      10
Name: count, dtype: int64

In [79]:
brand_list = ['Bajaj', 'Royal Enfield', 'Hero', 'Honda', 'Yamaha', 'TVS', 'KTM',
       'Suzuki', 'Harley-Davidson', 'Kawasaki', 'Hyosung', 'Mahindra',
       'Benelli', 'Triumph', 'Ducati', 'BMW']

# convert list into dictionary

In [80]:
# dt={}
# for i in range(1,len(brand_list)):
#     dt[brand_list[i]]=i

In [81]:
dt={item:i for i, item in enumerate(brand_list,start=1)}

In [82]:
dt

{'Bajaj': 1,
 'Royal Enfield': 2,
 'Hero': 3,
 'Honda': 4,
 'Yamaha': 5,
 'TVS': 6,
 'KTM': 7,
 'Suzuki': 8,
 'Harley-Davidson': 9,
 'Kawasaki': 10,
 'Hyosung': 11,
 'Mahindra': 12,
 'Benelli': 13,
 'Triumph': 14,
 'Ducati': 15,
 'BMW': 16}

In [83]:
catgorical['brand']=catgorical['brand'].map(dt)

In [84]:
dict={'First Owner':1,'Second Owner':2,'Third Owner':3,"Fourth Owner Or More":4}
catgorical['owner']=catgorical['owner'].map(dict)

In [85]:
catgorical['brand'].value_counts()

brand
1     2081
2     1346
3     1142
4      676
5      651
6      481
7      375
8      203
9       91
10      61
11      53
12      50
13      46
14      21
15      20
16      10
Name: count, dtype: int64

In [86]:
catgorical['owner_name']='shalu choudhary'
catgorical

,bike_name,city,owner,brand,owner_name
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,1,6,shalu choudhary
1,Royal Enfield Classic 350cc,Delhi,1,2,shalu choudhary
2,Triumph Daytona 675R,Delhi,1,14,shalu choudhary
3,TVS Apache RTR 180cc,Bangalore,1,6,shalu choudhary
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,1,5,shalu choudhary
...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,Delhi,1,3,shalu choudhary
9369,Bajaj Avenger 220cc,Bangalore,1,1,shalu choudhary
9370,Harley-Davidson Street 750 ABS,Jodhpur,1,9,shalu choudhary
9371,Bajaj Dominar 400 ABS,Hyderabad,1,1,shalu choudhary
9372,Bajaj Avenger Street 220,Hyderabad,1,1,shalu choudhary

In [87]:
catgorical.drop(['bike_name','city','owner_name'],axis=1,inplace=True)

In [88]:
catgorical

      owner  brand
0         1      6
1         1      2
2         1     14
3         1      6
4         1      5
...     ...    ...
9362      1      3
9369      1      1
9370      1      9
9371      1      1
9372      1      1

[7307 rows x 2 columns]

In [89]:
combined=pd.concat([catgorical,numerical],axis=1)
combined.head()

   owner  brand     price  kms_driven  age  power
0      1      6   35000.0     17654.0  3.0  110.0
1      1      2  119900.0     11000.0  4.0  350.0
2      1     14  600000.0       110.0  8.0  675.0
3      1      6   65000.0     16329.0  4.0  180.0
4      1      5   80000.0     10000.0  3.0  150.0

In [90]:
# divide x and y
# in x-->price
# in y --> other col

In [91]:
x=combined.drop('price',axis=1)
x

      owner  brand  kms_driven  age  power
0         1      6     17654.0  3.0  110.0
1         1      2     11000.0  4.0  350.0
2         1     14       110.0  8.0  675.0
3         1      6     16329.0  4.0  180.0
4         1      5     10000.0  3.0  150.0
...     ...    ...         ...  ...    ...
9362      1      3     48587.0  8.0  150.0
9369      1      1     60000.0  9.0  220.0
9370      1      9      3430.0  4.0  750.0
9371      1      1     21300.0  4.0  400.0
9372      1      1      7127.0  5.0  220.0

[7307 rows x 5 columns]

In [92]:
y=combined[['price']]
y

         price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
9362   25000.0
9369   35000.0
9370  450000.0
9371  139000.0
9372   80000.0

[7307 rows x 1 columns]

In [93]:
# Train testing split-->select random 80% part one side and 20% part another side
# does not divide by index
#xtrain--> x is used for the train purpose
#ytrain---> y is used for train purpose
#xtesting --> x is used for testing 
#ytesting--> y is used for testing

In [94]:
#scikit-learn--> it is a library which is used to defind function(predefined ) of ML

In [95]:
import sklearn

In [96]:
from sklearn.model_selection import train_test_split

In [99]:
x_train

NameError: name 'x_train' is not defined

In [100]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
# 20 %-->0.2
# when algo give the prediction for x variable it is called yhat
# test size=20% other remaining trainning --800

In [101]:
#linear regression
from sklearn.linear_model import LinearRegression

In [102]:
lg=LinearRegression()  # object of Linearregression class

In [103]:
## ALGORITHM TRAINNING
lg.fit(x_train,y_train) # training data for the trainning purpose

LinearRegression()

#step- modal evaluation [test modal]:- it is used to measure or the performance of a modal 
classfication and regression both have different method for evaluation

In [104]:
# training & testing
print("Trainning score",round(lg.score(x_train,y_train)*100,2))
print("Testing score",round(lg.score(x_test,y_test)*100,2))
# score  accuracy must be >=90

Trainning score 73.55
Testing score 75.7

In [ ]:
# diffrence between trainning or testing score is also not more than 5
#modal overfit or underfit or perfect (genralized modal)
# modal overfit--> training score ---> high
#                  testing score--->low
# then the modal is overfit
#modal underfit--> training score-->low
 #                  testing score--->either high or low

# GENRALIZED MODAL--->
# 1) diffrence not more than 5
# 2) modal overfit or modal underfit
# 3) score or accuracy HIGH in both case on train as well on test data

In [105]:
# prediction --> pass x data to the algo which is called y hat
# in this prediction is a y hat
y_hat=lg.predict(x_test)  #  for 1462 prediction

In [106]:
x_test.shape

(1462, 5)

In [107]:
y_test  # price in y test

         price
4117  105000.0
6294   97000.0
1857   47000.0
9206   28100.0
3142   37000.0
...        ...
8360   24000.0
8291   20000.0
3252   50000.0
6499   88000.0
2592   36900.0

[1462 rows x 1 columns]

In [ ]:
y_test['prediction']=y_hat

In [ ]:
y_test['prediction']=y_test['prediction'].map(lambda x:round(x,2))

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rdf=RandomForestRegressor()

In [ ]:
rdf.fit(x_train,y_train)

c:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor()

In [ ]:
print("Trainning score",round(rdf.score(x_train,y_train)*100,2))
print("Testing score",round(rdf.score(x_test,y_test['price'])*100,2))

Trainning score 98.27
Testing score 90.59

In [ ]:
# Save the variable/ modal  permanently import joblib and file extantion is lb 
ls=['shalu','vanshika','eun-woo','lee jong-sook']
ls

['shalu', 'vanshika', 'eun-woo', 'lee jong-sook']

In [ ]:
import joblib

In [ ]:
joblib.dump(ls,'k_friends.lb')

['k_friends.lb']

In [ ]:
ls

['shalu', 'vanshika', 'eun-woo', 'lee jong-sook']

In [ ]:
k_friends =joblib.load("k_friends.lb")
k_friends

['shalu', 'vanshika', 'eun-woo', 'lee jong-sook']

In [ ]:
joblib.dump(lg,'linear_regression.lb')

['linear_regression.lb']

In [ ]:
joblib.dump(lg,'linear_regression')

NameError: name 'joblib' is not defined